"""
Service to generate Python code equivalent for preprocessing operations.
This allows users to see and download the code that represents their UI actions.
"""

from typing import List, Optional


def generate_preprocessing_code(
    filename: str,
    missing_option: str,
    encoding_method: str,
    scaling_method: str,
    selected_columns: Optional[List[str]] = None
) -> str:
    """
    Generate Python code that replicates the preprocessing steps.
    
    Args:
        filename: Original dataset filename
        missing_option: Method for handling missing values
        encoding_method: Method for encoding categorical variables
        scaling_method: Method for scaling numerical features
        selected_columns: Optional list of columns to process
        
    Returns:
        Python code as a string
    """
    
    code_lines = [
        "# Auto-generated preprocessing code",
        "# Generated by ML Preprocessing Tool",
        "",
        "import pandas as pd",
        "import numpy as np",
    ]
    
    # Add imports based on what's needed
    imports = []
    if encoding_method == "Label Encoding":
        imports.append("from sklearn.preprocessing import LabelEncoder")
    if scaling_method in ["StandardScaler", "MinMaxScaler"]:
        imports.append(f"from sklearn.preprocessing import {scaling_method}")
    
    if imports:
        code_lines.extend(imports)
        code_lines.append("")
    
    # Load data
    code_lines.extend([
        "# Load the dataset",
        f"df = pd.read_csv('{filename}')",
        ""
    ])
    
    # Column selection
    if selected_columns:
        code_lines.extend([
            "# Select specific columns for processing",
            f"columns_to_process = {selected_columns}",
            "df_process = df[columns_to_process].copy()",
            "df_remaining = df.drop(columns=columns_to_process).copy()",
            ""
        ])
        df_var = "df_process"
    else:
        df_var = "df"
        code_lines.append("df_remaining = None")
    
    # Handle missing values
    code_lines.append("# Handle missing values")
    if missing_option == "Drop Rows":
        code_lines.append(f"{df_var}.dropna(inplace=True)")
        code_lines.extend([
            "if df_remaining is not None:",
            f"    df_remaining = df_remaining.loc[{df_var}.index]"
        ])
    elif missing_option == "Fill with Mean":
        code_lines.extend([
            f"numeric_cols = {df_var}.select_dtypes(include=np.number).columns",
            f"if not numeric_cols.empty:",
            f"    {df_var}[numeric_cols] = {df_var}[numeric_cols].fillna({df_var}[numeric_cols].mean())"
        ])
    elif missing_option == "Fill with Median":
        code_lines.extend([
            f"numeric_cols = {df_var}.select_dtypes(include=np.number).columns",
            f"if not numeric_cols.empty:",
            f"    {df_var}[numeric_cols] = {df_var}[numeric_cols].fillna({df_var}[numeric_cols].median())"
        ])
    elif missing_option == "Fill with Mode":
        code_lines.append(f"{df_var}.fillna({df_var}.mode().iloc[0], inplace=True)")
    
    code_lines.append("")
    
    # Outlier Detection
    if outlier_method != "None":
        code_lines.append("# Outlier Detection")
        code_lines.append(f"numeric_cols = {df_var}.select_dtypes(include=np.number).columns")
        code_lines.append("if not numeric_cols.empty:")
        
        if outlier_method == "Z-Score":
            code_lines.extend([
                "    from scipy import stats",
                f"    z_scores = np.abs(stats.zscore({df_var}[numeric_cols]))",
                f"    {df_var} = {df_var}[(z_scores < 3).all(axis=1)]"
            ])
        elif outlier_method == "IQR":
            code_lines.extend([
                f"    Q1 = {df_var}[numeric_cols].quantile(0.25)",
                f"    Q3 = {df_var}[numeric_cols].quantile(0.75)",
                "    IQR = Q3 - Q1",
                f"    condition = ~((({df_var}[numeric_cols] < (Q1 - 1.5 * IQR)) | ({df_var}[numeric_cols] > (Q3 + 1.5 * IQR))).any(axis=1))",
                f"    {df_var} = {df_var}[condition]"
            ])
            
        code_lines.extend([
            "    # Sync remaining df if rows were dropped",
            "    if df_remaining is not None:",
            f"        df_remaining = df_remaining.loc[{df_var}.index]",
            ""
        ])

    # Encoding categorical variables
    if encoding_method != "None":
        code_lines.append("# Encode categorical variables")
        code_lines.append(f"categorical_columns = {df_var}.select_dtypes(include=['object']).columns.tolist()")
        code_lines.append("")
        
        if encoding_method == "Label Encoding":
            code_lines.extend([
                "if categorical_columns:",
                "    for col in categorical_columns:",
                "        le = LabelEncoder()",
                f"        {df_var}[col] = le.fit_transform({df_var}[col].astype(str))"
            ])
        elif encoding_method == "One-Hot Encoding":
            code_lines.extend([
                "if categorical_columns:",
                f"    {df_var} = pd.get_dummies({df_var}, columns=categorical_columns)"
            ])
        
        code_lines.append("")
    
    # Feature Engineering
    if feature_engineering_method == "Polynomial Features":
        code_lines.append("# Feature Engineering: Polynomial Features")
        code_lines.extend([
            "from sklearn.preprocessing import PolynomialFeatures",
            f"numeric_cols = {df_var}.select_dtypes(include=np.number).columns.tolist()",
            "if numeric_cols:",
            "    poly = PolynomialFeatures(degree=2, include_bias=False)",
            f"    poly_features = poly.fit_transform({df_var}[numeric_cols])",
            "    feature_names = poly.get_feature_names_out(numeric_cols)",
            "    # Replace numeric columns with polynomial features",
            f"    df_poly = pd.DataFrame(poly_features, columns=feature_names, index={df_var}.index)",
            f"    {df_var} = {df_var}.drop(columns=numeric_cols)",
            f"    {df_var} = pd.concat([{df_var}, df_poly], axis=1)",
            ""
        ])

    # Scaling numerical features
    if scaling_method != "None":
        code_lines.append("# Scale numerical features")
        code_lines.append(f"numerical_columns = {df_var}.select_dtypes(include=['int64', 'float64']).columns.tolist()")
        code_lines.append("")
        
        if scaling_method in ["StandardScaler", "MinMaxScaler"]:
            code_lines.extend([
                "if numerical_columns:",
                f"    scaler = {scaling_method}()",
                f"    {df_var}[numerical_columns] = scaler.fit_transform({df_var}[numerical_columns])"
            ])
        
        code_lines.append("")
    
    # Merge back if needed
    code_lines.extend([
        "# Merge back processed columns with remaining columns if needed",
        "if df_remaining is not None:",
        f"    df_final = pd.concat([df_remaining, {df_var}], axis=1)",
        "else:",
        f"    df_final = {df_var}",
        ""
    ])

    # Save processed data
    code_lines.extend([
        "# Save the processed dataset",
        f"df_final.to_csv('processed_{filename}', index=False)",
        f"print(f'Processed data saved to processed_{filename}')"
    ])
    
    return "\n".join(code_lines)


def generate_pipeline_code(
    filename: str,
    missing_option: str,
    encoding_method: str,
    scaling_method: str,
    selected_columns: Optional[List[str]] = None
) -> str:
    """
    Generate scikit-learn Pipeline code for reproducible preprocessing.
    
    Returns:
        Python code for sklearn Pipeline that can be saved and reused
    """
    
    code_lines = [
        "# Scikit-learn Pipeline for reproducible preprocessing",
        "# This pipeline can be saved with joblib and reused on new data",
        "",
        "from sklearn.pipeline import Pipeline",
        "from sklearn.compose import ColumnTransformer",
        "from sklearn.impute import SimpleImputer",
    ]
    
    # Add specific imports
    if encoding_method == "Label Encoding":
        code_lines.append("from sklearn.preprocessing import LabelEncoder, OrdinalEncoder")
    elif encoding_method == "One-Hot Encoding":
        code_lines.append("from sklearn.preprocessing import OneHotEncoder")
    
    if scaling_method in ["StandardScaler", "MinMaxScaler"]:
        code_lines.append(f"from sklearn.preprocessing import {scaling_method}")
    
    code_lines.extend([
        "import pandas as pd",
        "",
        "# Load data",
        f"df = pd.read_csv('{filename}')",
        "",
        "# Define columns to process",
    ])

    if selected_columns:
        code_lines.append(f"selected_columns = {selected_columns}")
        # We need to intersect selected columns with type-specific columns
        code_lines.extend([
            "numeric_features = [c for c in df.select_dtypes(include=['int64', 'float64']).columns if c in selected_columns]",
            "categorical_features = [c for c in df.select_dtypes(include=['object']).columns if c in selected_columns]",
        ])
    else:
        code_lines.extend([
            "numeric_features = df.select_dtypes(include=['int64', 'float64']).columns.tolist()",
            "categorical_features = df.select_dtypes(include=['object']).columns.tolist()",
        ])

    code_lines.append("")
    
    # Build transformers
    code_lines.append("# Define preprocessing pipelines for different column types")
    
    # Numeric transformer
    numeric_steps = []
    if missing_option in ["Fill with Mean", "Fill with Median"]:
        strategy = "mean" if missing_option == "Fill with Mean" else "median"
        numeric_steps.append(f"('imputer', SimpleImputer(strategy='{strategy}'))")
    
    if scaling_method != "None":
        numeric_steps.append(f"('scaler', {scaling_method}())")
    
    if numeric_steps:
        code_lines.append(f"numeric_transformer = Pipeline(steps=[")
        for step in numeric_steps:
            code_lines.append(f"    {step},")
        code_lines.append("])")
        code_lines.append("")
    
    # Categorical transformer  
    if encoding_method != "None":
        cat_steps = []
        if missing_option == "Fill with Mode":
            cat_steps.append("('imputer', SimpleImputer(strategy='most_frequent'))")
        
        if encoding_method == "One-Hot Encoding":
            cat_steps.append("('onehot', OneHotEncoder(handle_unknown='ignore'))")
        elif encoding_method == "Label Encoding":
             # Sklearn pipelines don't support LabelEncoder on X easily, usually OrdinalEncoder is used for features
            cat_steps.append("('ordinal', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1))")

        if cat_steps:
            code_lines.append("categorical_transformer = Pipeline(steps=[")
            for step in cat_steps:
                code_lines.append(f"    {step},")
            code_lines.append("])")
            code_lines.append("")
    
    # Combine transformers
    code_lines.extend([
        "# Combine transformers",
        "preprocessor = ColumnTransformer(",
        "    transformers=["
    ])
    
    if numeric_steps:
        code_lines.append("        ('num', numeric_transformer, numeric_features),")
    if encoding_method != "None":
        # Check if we have categorical steps defined
        if 'categorical_transformer' in locals() or 'categorical_transformer' in "\n".join(code_lines):
             code_lines.append("        ('cat', categorical_transformer, categorical_features),")
    
    code_lines.extend([
        "    ],",
        "    remainder='passthrough'  # Keep other columns as is",
        ")",
        "",
        "# Fit and transform",
        "X = df.copy()",
        "X_processed = preprocessor.fit_transform(X)",
        "",
        "# Save pipeline for reuse",
        "import joblib",
        "joblib.dump(preprocessor, 'preprocessing_pipeline.pkl')",
        "",
        "# To use on new data:",
        "# preprocessor = joblib.load('preprocessing_pipeline.pkl')",
        "# X_new_processed = preprocessor.transform(X_new)"
    ])
    
    return "\n".join(code_lines)
