"""
Service to generate Python code equivalent for preprocessing operations.
This allows users to see and download the code that represents their UI actions.
"""

from typing import List, Optional

def generate_preprocessing_code(
    filename: str,
    missing_option: str,
    encoding_method: str,
    scaling_method: str,
    outlier_method: str = "None",
    feature_engineering_method: str = "None",
    remove_duplicates: bool = False,
    fix_numeric_formats: bool = False,
    fix_date_formats: bool = False,
    standardize_text: bool = False,
    date_feature_extraction: bool = False,
    text_feature_extraction: bool = False,
    rare_category_handling: bool = False,
    frequency_encoding: bool = False,
    target_encoding: bool = False,
    remove_high_correlation: bool = False,
    low_variance_filtering: bool = False,
    smote_oversampling: bool = False,
    target_column: Optional[str] = None,
    train_test_split: bool = False,
    test_size: float = 0.2,
    stratify: bool = False,
    selected_columns: Optional[List[str]] = None
) -> str:
    """
    Generate Python code that replicates the preprocessing steps using a leak-free Pipeline approach.
    """
    
    code_lines = [
        "# Auto-generated preprocessing code",
        "# Generated by ML Preprocessing Tool",
        "",
        "import pandas as pd",
        "import numpy as np",
        "from sklearn.model_selection import train_test_split",
        "from sklearn.pipeline import Pipeline",
        "from sklearn.compose import ColumnTransformer",
        "from sklearn.impute import SimpleImputer, KNNImputer",
        "from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, OneHotEncoder, OrdinalEncoder, LabelEncoder",
        "from sklearn.feature_selection import VarianceThreshold",
        "from scipy import stats",
        ""
    ]
    
    # Additional imports
    if smote_oversampling:
        code_lines.append("from imblearn.over_sampling import SMOTE")
    if target_encoding:
        code_lines.append("# pip install category_encoders")
        code_lines.append("from category_encoders import TargetEncoder")
    
    code_lines.append("")

    # 1. Load Data
    code_lines.extend([
        "# 1. Load Data",
        f"df = pd.read_csv('{filename}')",
        ""
    ])
    
    # Column selection
    if selected_columns:
        code_lines.extend([
            f"# Select specific columns",
            f"selected_columns = {selected_columns}",
            "df = df[selected_columns].copy()",
            ""
        ])

    # 2. Initial Cleaning (Applied to all data - Row wise operations that don't leak)
    code_lines.append("# 2. Initial Data Cleaning")
    
    if remove_duplicates:
        code_lines.append("df.drop_duplicates(inplace=True)")
    
    if fix_numeric_formats:
        code_lines.extend([
            "# Fix numeric formats",
            "for col in df.select_dtypes(include=['object']).columns:",
            "    try:",
            "        df[col] = df[col].astype(str).str.replace(r'[$,%]', '', regex=True)",
            "        df[col] = pd.to_numeric(df[col], errors='ignore')",
            "    except: pass"
        ])

    if standardize_text:
        code_lines.extend([
            "# Standardize text",
            "for col in df.select_dtypes(include=['object']).columns:",
            "    df[col] = df[col].astype(str).str.lower().str.strip()"
        ])
        
    if date_feature_extraction:
        code_lines.extend([
            "# Date Feature Extraction",
            "for col in df.select_dtypes(include=['datetime64', 'object']).columns:",
            "    try:",
            "        df[col] = pd.to_datetime(df[col])",
            "        df[col + '_year'] = df[col].dt.year",
            "        df[col + '_month'] = df[col].dt.month",
            "        df[col + '_day'] = df[col].dt.day",
            "        df[col + '_weekday'] = df[col].dt.weekday",
            "    except: pass"
        ])

    code_lines.append("")

    # 3. Train/Test Split
    code_lines.append("# 3. Train/Test Split (Crucial to prevent leakage)")
    if train_test_split:
        stratify_arg = f"df['{target_column}']" if stratify and target_column else "None"
        code_lines.extend([
            f"X = df.drop(columns=['{target_column}'])" if target_column else "X = df.copy()",
            f"y = df['{target_column}']" if target_column else "y = None",
            "",
            f"X_train, X_test, y_train, y_test = train_test_split(X, y, test_size={test_size}, stratify={stratify_arg}, random_state=42)",
            ""
        ])
    else:
        code_lines.extend([
            "# No split requested, but for ML best practice we treat full dataset as train",
            f"X_train = df.drop(columns=['{target_column}'])" if target_column else "X_train = df.copy()",
            f"y_train = df['{target_column}']" if target_column else "y_train = None",
            "X_test = None",
            ""
        ])

    # 4. Outlier Removal (Train Only)
    if outlier_method != "None":
        code_lines.append("# 4. Outlier Removal (Train Data Only)")
        code_lines.append("numeric_cols = X_train.select_dtypes(include=np.number).columns")
        
        if outlier_method == "Z-Score":
            code_lines.extend([
                "z_scores = np.abs(stats.zscore(X_train[numeric_cols].fillna(0)))",
                "mask = (z_scores < 3).all(axis=1)",
                "X_train = X_train[mask]",
                "if y_train is not None: y_train = y_train[mask]"
            ])
        elif outlier_method == "IQR":
            code_lines.extend([
                "Q1 = X_train[numeric_cols].quantile(0.25)",
                "Q3 = X_train[numeric_cols].quantile(0.75)",
                "IQR = Q3 - Q1",
                "mask = ~((X_train[numeric_cols] < (Q1 - 1.5 * IQR)) | (X_train[numeric_cols] > (Q3 + 1.5 * IQR))).any(axis=1)",
                "X_train = X_train[mask]",
                "if y_train is not None: y_train = y_train[mask]"
            ])
        code_lines.append("")

    # 5. Build Pipeline
    code_lines.append("# 5. Build Preprocessing Pipeline")
    code_lines.extend([
        "numeric_features = X_train.select_dtypes(include=['int64', 'float64']).columns.tolist()",
        "categorical_features = X_train.select_dtypes(include=['object', 'category']).columns.tolist()",
        "",
        "numeric_steps = []",
        "categorical_steps = []",
        ""
    ])

    # Imputation
    if missing_option == "Fill with Mean":
        code_lines.append("numeric_steps.append(('imputer', SimpleImputer(strategy='mean')))")
    elif missing_option == "Fill with Median":
        code_lines.append("numeric_steps.append(('imputer', SimpleImputer(strategy='median')))")
    elif missing_option == "Fill with Mode":
        code_lines.append("numeric_steps.append(('imputer', SimpleImputer(strategy='most_frequent')))")
        code_lines.append("categorical_steps.append(('imputer', SimpleImputer(strategy='most_frequent')))")
    elif missing_option == "KNN Imputation":
        code_lines.append("numeric_steps.append(('imputer', KNNImputer(n_neighbors=5)))")
    
    # Scaling
    if scaling_method == "StandardScaler":
        code_lines.append("numeric_steps.append(('scaler', StandardScaler()))")
    elif scaling_method == "MinMaxScaler":
        code_lines.append("numeric_steps.append(('scaler', MinMaxScaler()))")
    elif scaling_method == "RobustScaler":
        code_lines.append("numeric_steps.append(('scaler', RobustScaler()))")

    # Encoding
    if encoding_method == "One-Hot Encoding":
        code_lines.append("categorical_steps.append(('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False)))")
    elif encoding_method == "Label Encoding":
        code_lines.append("categorical_steps.append(('encoder', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)))")

    # Assemble Pipeline
    code_lines.extend([
        "",
        "preprocessor = ColumnTransformer(",
        "    transformers=[",
        "        ('num', Pipeline(numeric_steps), numeric_features),",
        "        ('cat', Pipeline(categorical_steps), categorical_features)",
        "    ],",
        "    remainder='passthrough'",
        ")",
        "",
        "pipeline = Pipeline(steps=[('preprocessor', preprocessor)])",
        ""
    ])

    # 6. Fit and Transform
    code_lines.append("# 6. Fit and Transform")
    code_lines.extend([
        "# Fit on Train ONLY",
        "pipeline.fit(X_train)",
        "",
        "# Transform Train and Test",
        "X_train_processed = pipeline.transform(X_train)",
        "if X_test is not None:",
        "    X_test_processed = pipeline.transform(X_test)",
        ""
    ])
    
    # 7. Save / Output
    code_lines.append("# 7. Output")
    code_lines.extend([
        "print('Preprocessing complete.')",
        "print(f'Train shape: {X_train_processed.shape}')",
        "if X_test is not None:",
        "    print(f'Test shape: {X_test_processed.shape}')"
    ])

    return "\n".join(code_lines)
